project_id = "bnzfdmxqjjgbsytazaau"

[functions.verify-recaptcha]
verify_jwt = false

[functions.r2-storage]
verify_jwt = false

[functions.migrate-to-r2]
verify_jwt = false

[functions.download-image]
verify_jwt = false

[functions.zip-upload]
verify_jwt = false

[functions.generate-thumbnail]
verify_jwt = false
